/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kis.view;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.attribute.BasicFileAttributes;
import java.nio.file.attribute.FileTime;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

import kis.controller.FileController;

/**
 *
 * @author sazevedo
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Class properties.
     */
    private File file;
    private String lastDirPath;
    private boolean decode;
    

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        // center frame in the screen.
        this.setLocationRelativeTo(null);
        
        // set window icon
        try {
            setIconImage(ImageIO.read(getClass().getResource("/kis/image/lock.gif")));
        }
        catch(Exception e) {
            System.err.println("Unable to load application icon");
        }
    }
    
    private void cleanUp() {
    this.file = null;
    this.jTextFieldPath.setText("");
    this.jLabelDataSize.setText("0 bytes.");
    this.jLabelDataType.setText("Unknown.");
    this.jLabelCreated.setText("Unkown.");
    this.jLabelModified.setText("Unkown.");
    this.jLabelStatus.setText("Encode");
    this.jCheckBoxRemoveOldFile.setSelected(false);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonBrowse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDataSize = new javax.swing.JLabel();
        jLabelDataType = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCreated = new javax.swing.JLabel();
        jLabelModified = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelStatus = new javax.swing.JLabel();
        jCheckBoxRemoveOldFile = new javax.swing.JCheckBox();
        jButtonExecute = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "File path"));

        jButtonBrowse.setText("...");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextFieldPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "File information"));

        jLabel1.setText("Size");

        jLabel2.setText("Type");

        jLabel3.setText("Modified");

        jLabelDataSize.setForeground(new java.awt.Color(0, 51, 204));
        jLabelDataSize.setText("0 bytes");

        jLabelDataType.setForeground(new java.awt.Color(0, 51, 204));
        jLabelDataType.setText("Unknown");

        jLabel6.setText("Created");

        jLabelCreated.setForeground(new java.awt.Color(0, 51, 204));
        jLabelCreated.setText("Unknown");

        jLabelModified.setForeground(new java.awt.Color(0, 51, 204));
        jLabelModified.setText("Unknown");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataSize)
                    .addComponent(jLabelDataType))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCreated))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModified)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelDataSize)
                    .addComponent(jLabel6)
                    .addComponent(jLabelCreated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabelDataType))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelModified)
                        .addContainerGap())))
        );

        jTextField1.setText("Operation");

        jLabelStatus.setText("Encode");

        jCheckBoxRemoveOldFile.setText("Remove old file");

        jButtonExecute.setText("Execute");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatus)
                .addGap(69, 69, 69)
                .addComponent(jCheckBoxRemoveOldFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonExecute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus)
                    .addComponent(jCheckBoxRemoveOldFile)
                    .addComponent(jButtonExecute)
                    .addComponent(jButtonCancel))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        
        JFileChooser chooser = new JFileChooser((this.lastDirPath != null) ? this.lastDirPath : System.getProperty("user.dir"));
        
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.jTextFieldPath.setText(chooser.getSelectedFile().getAbsolutePath());
            openFile(chooser.getSelectedFile());
        }
        
        
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        
        this.setVisible(false);
        this.dispose();
        
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonExecute;
    private javax.swing.JCheckBox jCheckBoxRemoveOldFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCreated;
    private javax.swing.JLabel jLabelDataSize;
    private javax.swing.JLabel jLabelDataType;
    private javax.swing.JLabel jLabelModified;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables

    private void openFile(File selectedFile) {
        if (!selectedFile.isFile()) {
            this.jLabelStatus.setText("Atention! Invalid file.");

            return;
        } 
    
        this.file = selectedFile;

        if (FileController.isKisFile(this.file)) {
            this.decode = true;
            this.jLabelStatus.setText("Decode");
        } 
        else {

            this.decode = false;
            this.jLabelStatus.setText("Encode");
        } 

        BasicFileAttributes attr;
        try {
            attr = Files.readAttributes(this.file.toPath(), BasicFileAttributes.class);
                    FileTime fileTime = attr.creationTime();
            this.lastDirPath = this.file.getPath().substring(0, this.file.getPath().indexOf(this.file.getName()));


            this.jLabelDataSize.setText(String.valueOf(this.file.length()) + " bytes.");
            this.jLabelDataType.setText(FileController.identifyFile(this.file));
            this.jLabelModified.setText((new SimpleDateFormat("MM/dd/yyyy - HH:mm")).format(new Date(this.file.lastModified())));
            this.jLabelCreated.setText((new SimpleDateFormat("MM/dd/yyyy - HH:mm")).format(new Date(fileTime.toMillis())));
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
